### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-top-ten#11]
On:
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_Release_Notes

Example:
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/OWASP_Top_Ten_2013/Top_10_2013-A4-Insecure_Direct_Object_References

**Comment by sslHello** [comment]
Hi,
thank you for your report,
Fixed by merge with branch 'design-update' and related fixes (2bcdece).
Entire Links up to A10:2017 should be OK now. Final 8 pages will be finally checked soon.
Cheers Torsten

**Comment by kingthorin** [comment]
Confirmed the specific item mentioned above has been fixed.

**Comment by sslHello** [comment]
Final 8 pages are checked and as far as I can see fixed now (commit 7445ce4).
Thanks for your volunteering.
Cheers Torsten
