### ISSUE TITLE
CWE ID and Description are mismatching

### ISSUE THREAD

**Issue by elayamathy** [OWASP/www-project-top-ten#2]
In https://github.com/OWASP/www-project-top-ten/blob/master/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure.md#external

The first entry "CWE-220: Exposure of sens. information through data queries" has the CWE ID as 220 but the following text "Exposure of sens. information through data queries" corresponds to CWE 202.

Please refer to following pages.
https://cwe.mitre.org/data/definitions/220.html
![image](https://user-images.githubusercontent.com/24566720/72828090-ee6c2280-3cb6-11ea-9a26-75e210847e18.png)

https://cwe.mitre.org/data/definitions/202.html
![image](https://user-images.githubusercontent.com/24566720/72828116-fa57e480-3cb6-11ea-8f50-6c556a6b2412.png)

**Comment by sslHello** [comment]
Hi,
thank you for your report,
Fixed by merge with branch 'design-update' and related fixes up to Commit be4094f.
Entire Links up to A10:2017 should be OK now. Final 8 pages will be finally checked soon.
Cheers Torsten

**Comment by sslHello** [comment]
Final 8 pages are checked and as far as I can see fixed now (commit 7445ce4).
Thanks for your volunteering.
Cheers Torsten
