### ISSUE TITLE
A10 Doesn't Redirect

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-top-ten#3]
https://www.owasp.org/index.php/Top_10-2017_A10-Insufficient_Logging%26Monitoring doesn't redirect to https://www2.owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A10-Insufficient_Logging%252526Monitoring.html (the other 9 seem to work fine).

Probably because of the weird `%252526`?

**Comment by kingthorin** [comment]
Note at this point you can't really change the `%252526` as people will already be linking to it, so the redirect 'rule' just needs to be corrected or properly formatted/implemented.

**Comment by kingthorin** [comment]
Oh and it seems the kind of previous/next buttons on the A# docs are hard coded to use `www2`

**Comment by sslHello** [comment]
Hi,
thank you for your report,
Fixed by merge with branch 'design-update' and related fixes up to Fixed by Commits 13aecf5 and 683a09d.
Entire Links up to A10:2017 should be OK now. Final 8 pages will be finally checked soon.
Cheers Torsten

**Comment by kingthorin** [comment]
The first link in the original report now 404s. However, on a positive note, I can confirm that using the next (right arrow) top of page links does now work between A9 and A10 (which was broken at the time of the original report.)

**Comment by sslHello** [comment]
Final 8 pages are checked and as far as I can see fixed now (commit 7445ce4).
Thanks for your volunteering.
Cheers Torsten
