### ISSUE TITLE
> Un pequeño informe sobre las vulnerabilidades ,ataques y puertas traceras sobre un sistema

### ISSUE THREAD

**Issue by timprivatelysleeps23** [OWASP/www-project-top-ten#51]
> Un pequeño informe sobre las vulnerabilidades ,ataques y puertas traceras sobre un sistema

_Originally posted by @timprivatelysleeps23 in https://github.com/OWASP/www-project-top-ten/issues/50#issuecomment-1397267738_

**Comment by TKMX-NC-TKMX** [comment]
>               > Un pequeño informe sobre las vulnerabilidades ,ataques y puertas traceras sobre un sistema
> 
> _Originally posted by @timprivatelysleeps23 in https://github.com/OWASP/www-project-top-ten/issues/50#issuecomment-1397267738_
>             

Tiene Copyright ok y lo he creado yo, el documento no es Open source
