### ISSUE TITLE
Dead url

### ISSUE THREAD

**Issue by cyanboy** [OWASP/www-project-top-ten#7]
The url for "OWASP Testing Guide: SQL Injection, Command Injection, and ORM Injection" - https://www2.owasp.org/www-project-testing/#div-downloads gives 404

**Comment by sslHello** [comment]
Hi,
thank you for your report.
Fixed by Commits 13aecf5 and 683a09d.
Entire Links up to A10:2017 should be OK now. Final 8 pages will be finally checked soon.
Cheers Torsten

**Comment by sslHello** [comment]
Final 8 pages are checked and as far as I can see fixed now (commit 7445ce4).
Thanks for your volunteering.
Cheers Torsten
